name: Project Test

on:
  push:

jobs:
   test:
      name: Project Bash Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Test Script
          run: bash cli.sh --help
        - name: Get Version
          run: bash cli.sh --version
        - name: Complete Job
          run: rm -rf ./*
